version: '3.7'

services:
# front
  front:
    image: clinic_front
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    container_name: clinic-front
    build:
      context: ./Clinic_front
      dockerfile: Dockerfile
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/default.conf
#      - ./Clinic_front:/app
#      - /app/node_modules
    ports:
       - 8080:80
       - 443:443
    volumes:
      - /etc/ssl/certs
      - /etc/ssl/private
    secrets:
      - source: clinic-ssl-key
        target: /etc/ssl/private/selfsigned.key
        mode: 0400  # Ограничение прав доступа к ключу
      - source: clinic-ssl-cert
        target: /etc/ssl/certs/selfsigned.crt
        mode: 0444  # Ограничение прав доступа к сертификату
    restart: unless-stopped
    depends_on:
      - back
#     restart_policy:
#        condition: on-failure
# back
    networks:
      - springboot-mysql-network
#
  back:
    image: clinic_back
    deploy:
      replicas: 1
    container_name: clinic-back
    build:
      context: ./Clinic
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    restart: on-failure
#    restart_policy:
#      condition: on-failure
    depends_on:
      - mysqldb
 #      mysqldb:
 #        condition: service_healthy
#    volumes: 
#      - ./Clinic/mysql-data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/clinic
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - springboot-mysql-network
 # Nginx service
#  webserver:
#    image: nginx:alpine
#    container_name: nginx-webserver
#    deploy:
#      replicas: 1
#      restart_policy:
#        condition: on-failure
#    ports:
#      - 80:80
#      - 443:443
#    secrets:
#      - source: clinic-ssl-key
#        target: /etc/ssl/private/selfsigned.key
#        mode: 0400  # Ограничение прав доступа к ключу
#      - source: clinic-ssl-cert
#        target: /etc/ssl/certs/selfsigned.crt
#        mode: 0444  # Ограничение прав доступа к сертификату
#
#    volumes:
#      - ./Clinic_front:/var/www/html
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - front
#    networks:
#      - springboot-mysql-network

  mysqldb:
    image: mysql:8.0.33
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./Clinic/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - springboot-mysql-network
 #   healthcheck:
 #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
 #     retries: 10
 #     interval: 3s
 #     timeout: 30s
secrets:
  clinic-ssl-key:
    external: true
  clinic-ssl-cert:
    external: true
volumes:
  mysql-data:
networks:
  springboot-mysql-network:
    name: springboot-mysql-network
