server:
  port: 9000
#  servlet:
#    session:
#      cookie:
#        http-only: false
#        secure: false
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/clinic
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
application:
  doctor:
    min-appointment-interval: 20
    max-allowed-appointments: 4
    tags: {"important":1,"ordinary":0}
